# Generated by Django 4.2 on 2023-04-20 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_paragraphitem_words'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ParagraphItem',
            new_name='ParagraphsGroup',
        ),
        migrations.RenameField(
            model_name='paragraphsgroup',
            old_name='paragraph',
            new_name='paragraphs',
        ),
    ]
