# Generated by Django 4.2 on 2023-04-21 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_paragraphitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ParagraphsGroup',
        ),
    ]
